export const products = [
    {
        _id: '1',
        name: 'Airpods wireless Bluetooth Headphone',
        image: '/images/airpods.jpg',
        description: 'Bluettoth headphones lets you connect it with compatible devices',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 0,
        rating:3.5,
        numReviews: 10,
    },
    {
        _id: '2',
        name: 'Alexa',
        image: '/images/alexa.jpg',
        description: 'Bluettoth headphones lets you connect it with compatible devices',
        brand: 'Apple',
        category: 'Electronics',
        price: 87.95,
        countInStock: 4.5,
        rating:4,
        numReviews: 2,
    },
    {
        _id: '3',
        name: 'Modern Camera',
        image: '/images/camera.jpg',
        description: 'Bluettoth headphones lets you connect it with compatible devices',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 4.5,
        rating:2.5,
        numReviews: 12,
    },
    {
        _id: '4',
        name: 'Phone',
        image: '/images/phone.jpg',
        description: 'Bluettoth headphones lets you connect it with compatible devices',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 4.5,
        rating:4.5,
        numReviews: 12,
    },
    {
        _id: '5',
        name: 'Mouse',
        image: '/images/mouse.jpg',
        description: 'Bluettoth headphones lets you connect it with compatible devices',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 4.5,
        rating: 4.5,
        numReviews: 12,
    },
    {
        _id: '6',
        name: 'Sample',
        image: '/images/sample.jpg',
        description: 'Bluettoth headphones lets you connect it with compatible devices',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 4.5,
        rating:4.5,
        numReviews: 12,
    },
    {
        _id: '7',
        name: 'Airpods wireless Bluetooth Headphone',
        image: '/images/mouse.jpg',
        description: 'Bluettoth headphones lets you connect it with compatible devices',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 4.5,
        rating:4.5,
        numReviews: 12,
    },
    {
        _id: '8',
        name: 'Airpods wireless Bluetooth Headphone',
        image: '/images/playstation.jpg',
        description: 'Bluettoth headphones lets you connect it with compatible devices',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 4.5,
        rating:4.5,
        numReviews: 12,
    }
]